export const ListData = [
        {
            createCard: true,
            completed: true,
        },
        {
            heading: 'B.E ECE SEM2',
            branch: 'B.E',
            department: 'ECE',
            semester: '2',
            subject: '5',
            lab: '2',
            ExamType: 'Semester',
            completed: true,
            id: 0,
        },
        {
            heading: 'B.E EEE SEM 2',
            branch: 'B.E',
            department: 'EEE',
            semester: '2',
            subject: '5',
            lab: '2',
            ExamType: 'Semester',
            completed: true,
            id: 1,
        },
        {
            heading: 'B.E MECH SEM2',
            branch: 'B.E',
            department: 'MECH',
            semester: '2',
            subject: '3',
            lab: '0',
            ExamType: 'Semester',
            completed: false,
            id: 2,
        },
        {
            heading: 'B.E CSE SEM 2',
            branch: 'B.E',
            department: 'CSE',
            semester: '2',
            subject: '4',
            lab: '0',
            ExamType: 'Internal',
            completed: false,
            id: 3,
        },
        {
            heading: 'B.TECH IT SEM2',
            branch: 'B.TECH',
            department: 'IT',
            semester: '2',
            subject: '4',
            lab: '0',
            ExamType: 'Model',
            completed: true,
            id: 4,
        },
    ]