export const StudentData=[
    {
        sn:"1",
        regno:"19TUEE101",
        name:"Sreedhar",
        dep:"ECE",
        seatno:"1"
    },
    {
        sn:"2",
        regno:"19TUEE102",
        name:"Praveena",
        dep:"ECE",
        seatno:"2"
    },
    {
        sn:"3",
        regno:"19TUEE103",
        name:"Rohit",
        dep:"ECE",
        seatno:"3"
    },
    {
        sn:"4",
        regno:"19TUEE104",
        name:"Nisha",
        dep:"ECE",
        seatno:"4"
    },
    {
        sn:"5",
        regno:"19TUEE105",
        name:"Nivi",
        dep:"ECE",
        seatno:"5"
    },
    {
        sn:"6",
        regno:"19TUEE106",
        name:"Sharan",
        dep:"ECE",
        seatno:"6"
    },
    {
        sn:"7",
        regno:"19TUEE107",
        name:"Sharmila",
        dep:"ECE",
        seatno:"7"
    },
    {
        sn:"8",
        regno:"19TUEE108",
        name:"Jungkook",
        dep:"ECE",
        seatno:"8"
    },
    {
        sn:"9",
        regno:"19TUEE109",
        name:"Jhope",
        dep:"ECE",
        seatno:"9"
    },
    {
        sn:"10",
        regno:"19TUEE110",
        name:"Jin",
        dep:"ECE",
        seatno:"10"
    },
    {
        sn:"11",
        regno:"19TUEE111",
        name:"Suga",
        dep:"ECE",
        seatno:"11"
    },
    {
        sn:"12",
        regno:"19TUEE112",
        name:"Jimin",
        dep:"ECE",
        seatno:"12"
    },
    {
        sn:"13",
        regno:"19TUEE113",
        name:"Tayung",
        dep:"ECE",
        seatno:"13"
    },
    {
        sn:"14",
        regno:"19TUEE114",
        name:"Pramesh",
        dep:"ECE",
        seatno:"14"
    },
]